use_frameworks!

target 'SGSHTTPModule_Example' do
  pod 'SGSHTTPModule', :path => '../'

  target 'SGSHTTPModule_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
